### ISSUE TITLE
vboxsf check from …/installers/linux.rb fails with (at least) VirtualBox 6.0.6

### ISSUE THREAD

**Issue by jubalfh** [dotless-de/vagrant-vbguest#337]
This seems to be caused by check for vboxsf see relevant part of the logs + some context:

```sh
DEBUG guest: Trying: redhat
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /etc/redhat-release (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
 INFO guest: Detected: redhat!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: test -f /etc/centos-release (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "d340c071-593a-4880-bd64-2e80211168d4", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="mgt"
[stdout output removed for clarity]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: VBoxService --version (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0

> DEBUG ssh: Re-using SSH connection.
>  INFO ssh: Execute: lsmod | grep vboxsf (sudo=true)
> DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
> DEBUG ssh: Exit status: 1

DEBUG vbguest-machine: Current states for VM 'mgt' are : guest_version=6.0.6 : host_version=6.0.6 : running=false
 INFO interface: warn: [mgt] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
[mgt] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
```

Forcing the module to be loaded at the boot seems to work fine as a workaround:
```ruby
  config.vm.provision "shell", run: "always", inline: <<-WORKAROUND
    modprobe vboxsf || true
  WORKAROUND
```

_Originally posted by @jubalfh in https://github.com/dotless-de/vagrant-vbguest/issues/278#issuecomment-490542673_

**Comment by jubalfh** [comment]
This seems to be the [relevant code](https://github.com/dotless-de/vagrant-vbguest/blob/934fd22864c811c951c020cfcfc5c2ef9d79d5ef/lib/vagrant-vbguest/installers/linux.rb#L77-L82):

```ruby
      def running?(opts=nil, &block)
        opts = {
          :sudo => true
        }.merge(opts || {})
        communicate.test('lsmod | grep vboxsf', opts, &block)
      end
```
Note that the check will fail even if the VboxService is happily running.

**Comment by Deaton64** [comment]
Hi,

I get the same thing on: Windows 10 host, Vagrant 2.2.4, Virtual Box 6.0.6, vbguest 0.17.2. VM OS Centos 7, Centos 6, Ubuntu 12

Although, strangely it just worked fine. I'm also getting a lot of broken pipe messages, where everything was working fine. So maybe something has changed on Vagrant or Virtual Box to cause this issue.

David

**Comment by karousn** [comment]
the same here +1

**Comment by davidgreisler** [comment]
I have the same issue. The workaround posted by @jubalfh does not work for me.

    ==> default: Machine booted and ready!
    [default] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
    bash: line 5: setup: command not found
    ==> default: Checking for guest additions in VM...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
    
     setup
    
    Stdout from the command:
    
    
    
    Stderr from the command:
    
    bash: line 5: setup: command not found

**Host OS:** Ubuntu 19.04
**Guest OS:** Debian Stretch
**VirtualBox** 6.0.6-dfsg-1
**Vagrant** 2.2.3+dfsg-1ubuntu2
**vagrant-vbguest**: 0.17.2

Is there any other information that I could provide that would help resolving this issue?

**Comment by TonyApuzzo** [comment]
A mild improvement to the workaround is to enable vbguest auto install only on first provisioning, for example:

```ruby
Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    # Check for and install VB Guest Additions only on the very first provision
    config.vbguest.auto_update = !Dir['.vagrant/machines/default/*/action_provision'].any?
  end
  
end
```

**Comment by davidgreisler** [comment]
I've also added the workaround from @TonyApuzzo and now my Vagrant box works again, thanks!

**Comment by promethe42** [comment]
Same here with an Ubuntu 18.04 box and VirtualBox 6.0.8.

**Comment by Toilal** [comment]
I think it's fixed in 0.18.0 (new release), you should all give it a try.

**Comment by TonyApuzzo** [comment]
It was still failing with Vagrant 2.2.5 plugin 0.18.0 on Centos/7 box version 1901.2 and Virtualbox 6.0.8 Windows 10 host for me, but I didn't/don't have time right now to write up findings... sorry!

**Comment by Deaton64** [comment]
It's not fixed for me. Windows 10, VirtualBox 6.0.8, Vagrant 2.2.4, VBGuest plugin 0.18.0.
Box boots with no guest additions installed and as expected, guest additions is installed by the plugin. Next time the box boots, I get the message that guest additions is installed but not running and the plugin tries to install it all again.
If I remove the plugin after the first boot and install of guest additions, the box runs fine with Vagrant mapping drives as expected, so guest additions is running.

**Comment by fnordfish** [comment]
Too bad! @Deaton64 which base box (guest OS) are you using?

--  
Robert Schulze

**Comment by Deaton64** [comment]
Yes, that would help. Centos 6 & 7. @fnordfish

**Comment by promethe42** [comment]
Updating to 0.18.0 fixed it for me.
Host: Ubuntu 18.04
Guest: Ubuntu 18.04

**Comment by karousn** [comment]
@promethe42 version VirtualBox ?
> 
> 
> Updating to 0.18.0 fixed it for me.
> Host: Ubuntu 18.04
> Guest: Ubuntu 18.04

**Comment by promethe42** [comment]
VirtualBox 6.0
