### ISSUE TITLE
0.22 is broken - Guest additions keep being uninstalled/reinstalled

### ISSUE THREAD

**Issue by agilis1** [dotless-de/vagrant-vbguest#362]
Upgraded from version 0.21 to 0.22 and now when the guest is rebooted, the guest additions are reinstalled, even tho the guest additions are the correct version.

```
Fetching: vagrant-vbguest-0.22.0.gem (100%)
Successfully uninstalled vagrant-vbguest-0.21.0
Updated 'vagrant-vbguest' to version '0.22.0'!
```

```
Installing Virtualbox Guest Additions 6.0.14 - guest version is 6.0.14
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.0.14 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 6.0.14 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
3.10.0-1062.7.1.el7.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
An error occurred during installation of VirtualBox Guest Additions 6.0.14. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Paul M/Projects/centos-docker
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

This same behavior occurs anytime the guest is rebooted.

When running is it as a command...

```
PS C:\Vagrant\X11> vagrant vbguest --status
[default] A Virtualbox Guest Additions installation was found but no tools to rebuild or start them.
PS C:\Vagrant\X11> vagrant vbguest --do install
[default] A Virtualbox Guest Additions installation was found but no tools to rebuild or start them.
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.math.princeton.edu
 * epel: packages.oit.ncsu.edu
 * extras: repo1.sea.innoscale.net
 * remi-php56: mirror.pit.teraswitch.com
 * remi-safe: mirror.pit.teraswitch.com
 * updates: ftp.usf.edu
Package kernel-devel-3.10.0-1062.7.1.el7.x86_64 already installed and latest version
Package kernel-devel-3.10.0-1062.4.1.el7.x86_64 already installed and latest version
Package gcc-4.8.5-39.el7.x86_64 already installed and latest version
Package binutils-2.27-41.base.el7_7.1.x86_64 already installed and latest version
Package 1:make-3.82-24.el7.x86_64 already installed and latest version
Package 4:perl-5.16.3-294.el7_6.x86_64 already installed and latest version
Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
Package elfutils-libelf-devel-0.176-2.el7.x86_64 already installed and latest version
Nothing to do
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Forcing installation of Virtualbox Guest Additions 6.0.14 - guest version is 6.0.14
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.0.14 Guest Additions for Linux........
VirtualBox Guest Additions installer
VBoxControl: error: Could not contact the host system.  Make sure that you are running this
VBoxControl: error: application inside a VirtualBox guest system, and that you have sufficient
VBoxControl: error: user permissions.
This system appears to have a version of the VirtualBox Guest Additions
already installed.  If it is part of the operating system and kept up-to-date,
there is most likely no need to replace it.  If it is not up-to-date, you
should get a notification when you start the system.  If you wish to replace
it with this version, please do not continue with this installation now, but
instead remove the current version first, following the instructions for the
operating system.

If your system simply has the remains of a version of the Additions you could
not remove you should probably continue now, and these will be removed during
installation.

Do you wish to continue? [yes or no]
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
3.10.0-1062.4.1.el7.x86_64.
ERROR: Can't map '//etc/selinux/targeted/policy/policy.31':  Invalid argument

ERROR: Unable to open policy //etc/selinux/targeted/policy/policy.31.
libsemanage.semanage_read_policydb: Error while reading kernel policy from /etc/selinux/targeted/active/policy.kern. (No such fil
e or directory).
OSError: No such file or directory
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
```

https://stackoverflow.com/questions/59179637/vagrant-up-causes-guest-additions-to-reinstall-each-time-why/59185016#59185016

**Comment by fnordfish** [comment]
Darn! Thanks for reporting.

Anyone: Until I can fix it (PR very welcome) please downgrade to `0.21` or set `config.vbguest.auto_update = false` and run vbguest manually

**Comment by agilis1** [comment]
**Steps to downgrade to .21:**

1. `vagrant plugin uninstall vagrant-vbguest`
Uninstalling the 'vagrant-vbguest' plugin...
Successfully uninstalled micromachine-3.0.0
Successfully uninstalled vagrant-vbguest-0.22.0

2.  `vagrant plugin install vagrant-vbguest --plugin-version 0.21`
Installing the 'vagrant-vbguest --version '0.21'' plugin. This can take a few minutes...
Fetching: micromachine-3.0.0.gem (100%)
Fetching: vagrant-vbguest-0.21.0.gem (100%)
Installed the plugin 'vagrant-vbguest (0.21.0)'!

**Comment by agilis1** [comment]
My colleague is on v0.21, same as me, and we cannot prevent the vbguest plugin from installing each time the guest is reloaded. We are both using the following:
vagrant-vbguest: v0.21
vagrant v2.2.6
VirtualBox 6.0.14

No matter what I try, this occurs:
`[default] A Virtualbox Guest Additions installation was found but no tools to rebuild or start them.`

I have tried uninstalling the plugin and reinstalling.
I have tried uninstalling the guest additions from the guest manually.

Their machine just will not stop trying to reinstall.

I know that when I updated to v0.22, I had the same issue. But once I went to v0.21, no issues.

**Comment by fnordfish** [comment]
fixed in 0.22.1

**Comment by rubo77** [comment]
I have the same problem with vagrant-vbguest (0.23.0, global)

**Comment by smdsbz** [comment]
Still having this issue with 0.29 and CentOS 7 box.

Downgrading to 0.21 works, but got `No presto metadata available for C7.8.2003-base` and running exceptionally slow ([here](https://stackoverflow.com/questions/37030605/no-presto-metadata-available-for-base-error-downloading-packages)'s a link fyr).

**Comment by b-long** [comment]
The bug also exists using vagrant-vbguest (0.30.0, global) with Fedora 28. 

```
config.vm.box_url = "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-28-1.1.x86_64.vagrant-virtualbox.box"
```
